### ISSUE TITLE
Suggestion: file to be included as <script>

### ISSUE THREAD

**Issue by ianengelbrecht** [ericnograles/browser-image-resizer#6]
It would be great to have a version of this that I could simply include using a <script> for cases where I'm not using any kind of build system

**Comment by isvladxxe** [comment]
Try to use browser es6 modules
or build for browser js

example 
```
import readAndCompressImage  from 'browser-image-resizer'
window.readAndCompressImage = readAndCompressImage
```

but not recommended

**Comment by ericnograles** [comment]
Sorry for the long delay on this @ianengelbrecht @isvladxxe I lost track of this issue.  I'll push out something to a CDN with the prebuilt JS and let you guys know when you can try it.

**Comment by ianengelbrecht** [comment]
Thanks Eric

**Comment by ericnograles** [comment]
@ianengelbrecht @isvladxxe give this a shot for in-browser:

```
<script src="https://cdn.jsdelivr.net/gh/ericnograles/browser-image-resizer@2.0.0/dist/index.js"></script>
```

The corresponding PR is #8 and I've cut a new major release (v2.0.0) which will land in NPM since I restructured how to get at `readAndCompressImage`. Instead of being the default export, it's a named export and can be accessed using a destructuring statement like so:

```
import { readAndCompressImage } from 'browser-image-resizer';
```
